### ISSUE TITLE
why move to the other direction?

### ISSUE THREAD

**Issue by nicoster** [GamendeMier/cargame#1]
any reason for moving to Lua from TS. 
as I'm about to port a Lua project to TS using `tstl`.

**Comment by mierenhoop** [comment]
The reason I ported the project from Typescript to Lua was first of all, because the code required an extra step to compile. Now that's not a big problem as it's quite fast, but it seems kind of unnecessary. Secondly the two main reasons for choosing Typescript were better tooling and classes. The tooling was definitely a big thing for me, mainly auto completion. As of recently I discovered a language server for Lua, which works good enough. Classes were also a nice thing to have in Typescript, but they're very easily replicated in Lua, see http://lua-users.org/wiki/SimpleLuaClasses. The type system of Typescript meant that you have to write more boilerplate code to let the compiler know you don't do anything out of order, which is a good thing but kind of defeats the purpose of the Love2d game engine which is to create a game easily with minimal code, not to mention the bindings you have to create for libraries. I understand why one might choose Typescript over Lua, but in my opinion it's not a must have for such a simple game.
